name: Build and Publish Library with Maven
on:
  push:
  workflow_dispatch:

jobs:
  build:
    uses: statens-pensjonskasse/github-actions-library/.github/workflows/build-library-maven.yaml@fb0c09dd23612b245f1abb637a0537e93ab8d1c2 # v1.20.3
    permissions:
      contents: write
      packages: write
    secrets: inherit
    with:
      java-version: '21'
      slack-channel: '#panda-ci'
      slack-bot-name: "GitHub Actions"
      slack-bot-icon: ':panda_face:'