name: Build and Publish Library with Maven
on:
  push:
  workflow_dispatch:

jobs:
  build:
    uses: statens-pensjonskasse/github-actions-library/.github/workflows/build-library-maven.yaml@80519616fb61d53581b05d706e1a1f56eb541513 # v1.19.2
    permissions:
      contents: write
      packages: write
    secrets: inherit
    with:
      java-version: '21'
      slack-channel: '#panda-ci'
      slack-bot-name: "GitHub Actions"
      slack-bot-icon: ':panda_face:'