name: Bygg og release artifakt med Maven
on:
  push:
  workflow_dispatch:
jobs:
  build:
    uses: statens-pensjonskasse/public-actions-library/.github/workflows/build-library-maven.yaml@72d62357095b14b3ee23b8fa9012acd00fc40f90 # v0.2.10
    permissions:
      contents: write
      packages: write
    secrets: inherit
    with:
      java-version: '21'
      require-release-flag: true # Lag release hvis commit har [release] i commit-meldingen
