name: Build and Publish Library with Maven
on:
  push:
  workflow_dispatch:

jobs:
  build:
    uses: statens-pensjonskasse/github-actions-library/.github/workflows/build-library-maven.yaml@c0b167fac3e975fc2e55e160f30076f192d78692 # v1.27.1
    permissions:
      contents: write
      packages: write
    secrets: inherit
    with:
      java-version: '21'
      slack-channel: '#panda-ci'
      slack-bot-name: "GitHub Actions"
      slack-bot-icon: ':panda_face:'