name: Build and Publish Library with Maven
on:
  push:
  workflow_dispatch:

jobs:
  build:
    uses: statens-pensjonskasse/github-actions-library/.github/workflows/build-library-maven.yaml@bc1c17a29b8c8424f84005ee26e01cf457c2c416 # v1.17.7
    permissions:
      contents: write
      packages: write
    secrets: inherit
    with:
      java-version: '21'
      slack-channel: '#panda-ci'
      slack-bot-name: "GitHub Actions"
      slack-bot-icon: ':panda_face:'