name: Bygg og release artifakt med Maven
on:
  push:
  workflow_dispatch:
jobs:
  build:
    uses: statens-pensjonskasse/public-actions-library/.github/workflows/build-library-maven.yaml@b9ffe33a4cf5629272bb88a89ebb9045b17de6bb # v0.3.1
    permissions:
      contents: write
      packages: write
    secrets: inherit
    with:
      java-version: '21'
      require-release-flag: true # Lag release hvis commit har [release] i commit-meldingen
