name: Bygg og release artifakt med Maven
on:
  push:
  workflow_dispatch:
jobs:
  build:
    uses: statens-pensjonskasse/public-actions-library/.github/workflows/build-library-maven.yaml@04b1606a939935f7ef9b875107cfdd4776549dcb # v0.2.8
    permissions:
      contents: write
      packages: write
    secrets: inherit
    with:
      java-version: '21'
      require-release-flag: true # Lag release hvis commit har [release] i commit-meldingen
